export type Profile = { uid:string; name:string; avatar:string };
export type Post = { id:string; uid:string; name:string; avatar:string; text:string; topic:string; mood:string; createdAt:number };
export type Reply = { id:string; uid:string; name:string; avatar:string; text:string; createdAt:number };
export type Message = { id:string; uid:string; text:string; createdAt:number };
export type Room = { id:string; members:string[]; names:Record<string,string>; createdAt:number };
export const topics = ['Todo','Vida cotidiana','Relaciones','Universidad','Ansiedad','Amistad','Pequeñas victorias'];
export const moods = [{emoji:'🌤️',label:'En calma'},{emoji:'🌧️',label:'Triste'},{emoji:'🌀',label:'Con ansiedad'},{emoji:'🌱',label:'Con esperanza'},{emoji:'🔥',label:'Frustrado'}];
export const examples:Post[] = [];
export const exampleReplies:Record<string,Reply[]> = {};
export function ago(date:number){ const m=Math.max(0,Math.floor((Date.now()-date)/60000)); return m<1?'Ahora':m<60?`Hace ${m} min`:m<1440?`Hace ${Math.floor(m/60)} h`:new Date(date).toLocaleDateString('es'); }
