import {useEffect,useRef,useState} from 'react';
import {Camera,ChevronLeft,ImagePlus,MessageCircle,Plus,Send,Trash2,X} from 'lucide-react';
import {topics,type Message,type Post,type Profile,type Room} from './data';
import * as store from './store';
import './polish.css';
type View='feed'|'categories'|'chat';
const avatars=['🪐','🌙','🌱','🌊','🌻','🦊','🐢','🍄'];
const cats=['Todo',...topics.slice(1)];
const err=(e:unknown)=>e instanceof Error&&e.message.length<120?e.message:'No se pudo completar. Inténtalo de nuevo.';
function Dialog({title,children,close}:{title:string;children:React.ReactNode;close:()=>void}){return <div className="p-shade"><section className="p-dialog"><header><button onClick={close}><ChevronLeft/></button><b>{title}</b><button onClick={close}><X/></button></header>{children}</section></div>}
export default function App(){const [profile,setProfile]=useState<Profile|null>(null),[posts,setPosts]=useState<Post[]>([]),[view,setView]=useState<View>('feed'),[topic,setTopic]=useState('Todo'),[compose,setCompose]=useState(false),[detail,setDetail]=useState<Post|null>(null),[room,setRoom]=useState<string|null>(null),[notice,setNotice]=useState('');const fail=(e:unknown)=>setNotice(err(e));useEffect(()=>{let stop=()=>{};store.connect().then(p=>{setProfile(p);stop=store.watchPosts(setPosts,fail)}).catch(fail);return()=>stop()},[]);useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(t)},[notice]);const filtered=posts.filter(p=>topic==='Todo'||p.topic===topic);const chat=async(p:Post)=>{if(!profile)return;try{setRoom(await store.createRoom(profile,p));setDetail(null);setView('chat')}catch(e){fail(e)}};return <main className="polish"><header className="p-top"><button onClick={()=>setView('categories')}>☰</button><b>{view==='categories'?'Todas las categorías':view==='chat'?'Chats':'Hombro Enemigo'}</b><span/></header>{!profile?.name?<Identity profile={profile} done={setProfile} fail={fail}/>:view==='categories'?<section className="p-cats">{cats.map((c,i)=><button className={`c${i%8}`} onClick={()=>{setTopic(c);setView('feed')}} key={c}>{c}</button>)}</section>:view==='chat'?<Chats profile={profile} room={room} setRoom={setRoom} fail={fail}/>:<section className="p-feed">{filtered.length?filtered.map(p=><article className="p-post" key={p.id} onClick={()=>setDetail(p)}><span className="p-avatar">{p.avatar}</span><div><b>@{p.name}</b><small>{p.topic}</small></div>{p.media&&<Camera className="p-camera" size={17}/>}<p>{p.text}</p></article>):<div className="p-empty">No hay desahogos en esta categoría.</div>}</section>}<nav className="p-nav"><button className={view==='feed'?'active':''} onClick={()=>setView('feed')}>Inicio</button><button onClick={()=>setView('categories')}>Categorías</button><button onClick={()=>setView('chat')}>Chats</button></nav>{profile&&view==='feed'&&<button className="p-plus" onClick={()=>setCompose(true)}><Plus/></button>}{compose&&profile&&<Composer profile={profile} close={()=>setCompose(false)} done={()=>{setCompose(false);setNotice('Publicado.')}} fail={fail}/>} {detail&&profile&&<Detail post={detail} profile={profile} close={()=>setDetail(null)} chat={chat} fail={fail}/>} {notice&&<div className="p-notice">{notice}</div>}</main>}
function Identity({profile,done,fail}:{profile:Profile|null;done:(p:Profile)=>void;fail:(e:unknown)=>void}){const [name,setName]=useState(''),[avatar,setAvatar]=useState(avatars[0]);if(!profile)return null;return <Dialog title="Tu identidad" close={()=>{}}><form className="p-form" onSubmit={async e=>{e.preventDefault();try{const p={...profile,name:name.trim(),avatar};await store.upsertProfile(p);done(p)}catch(e){fail(e)}}}><input autoFocus placeholder="Tu nombre" minLength={2} required value={name} onChange={e=>setName(e.target.value)}/><div className="p-avatars">{avatars.map(a=><button type="button" className={a===avatar?'on':''} onClick={()=>setAvatar(a)} key={a}>{a}</button>)}</div><button className="p-primary">Entrar</button></form></Dialog>}
function Composer({profile,close,done,fail}:{profile:Profile;close:()=>void;done:()=>void;fail:(e:unknown)=>void}){const [text,setText]=useState(''),[topic,setTopic]=useState(topics[1]),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false);return <Dialog title="Escribir desahogo" close={close}><form className="p-form p-compose" onSubmit={async e=>{e.preventDefault();setBusy(true);try{const media=file?await store.uploadImage(file,'posts',profile.uid):undefined;await store.publish({...profile,text:text.trim()||'Imagen',topic,mood:'🌤️',createdAt:Date.now(),media});done()}catch(e){fail(e)}finally{setBusy(false)}}}><textarea placeholder="Desahogar..." value={text} onChange={e=>setText(e.target.value)}/><select value={topic} onChange={e=>setTopic(e.target.value)}>{topics.slice(1).map(t=><option key={t}>{t}</option>)}</select><label className="p-upload"><ImagePlus/> {file?file.name:'Añadir imagen'}<input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><button className="p-primary" disabled={busy||(!text&&!file)}>{busy?'Subiendo…':'Publicar'}</button></form></Dialog>}
function Detail({post,profile,close,chat,fail}:{post:Post;profile:Profile;close:()=>void;chat:(p:Post)=>void;fail:(e:unknown)=>void}){return <Dialog title={post.name} close={close}><section className="p-detail"><p>{post.text}</p>{post.media&&<img src={post.media.url} alt="Imagen del desahogo"/>}<div className="p-detail-actions">{post.uid!==profile.uid&&<button className="p-primary" onClick={()=>chat(post)}><MessageCircle/> Conversar</button>}{post.uid===profile.uid&&<button className="p-danger" onClick={async()=>{try{await store.removePost(post.id);close()}catch(e){fail(e)}}}><Trash2/> Eliminar</button>}</div></section></Dialog>}
function Chats({profile,room,setRoom,fail}:{profile:Profile;room:string|null;setRoom:(id:string|null)=>void;fail:(e:unknown)=>void}){const [rooms,setRooms]=useState<Room[]>([]),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(''),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false);useEffect(()=>store.watchRooms(profile.uid,setRooms,fail),[profile.uid]);useEffect(()=>{if(!room){setMessages([]);return}return store.watchMessages(room,setMessages,fail)},[room]);const current=rooms.find(r=>r.id===room);const name=(r:Room)=>Object.entries(r.names).find(([id])=>id!==profile.uid)?.[1]??'Chat';if(!current)return <section className="p-rooms">{rooms.map(r=><button onClick={()=>setRoom(r.id)} key={r.id}><b>{name(r)}</b><small>Conversación privada</small></button>)}{!rooms.length&&<div className="p-empty">Abre un desahogo y toca Conversar.</div>}</section>;return <section className="p-chat"><header><button onClick={()=>setRoom(null)}><ChevronLeft/></button><b>{name(current)}</b></header><div className="p-messages">{messages.map(m=><div className={m.uid===profile.uid?'mine':''} key={m.id}>{m.text&&<p>{m.text}</p>}{m.media&&<img src={m.media.url} alt="Imagen del chat"/>}</div>)}</div><form onSubmit={async e=>{e.preventDefault();if(!text&&!file)return;setBusy(true);try{const media=file?await store.uploadImage(file,'chats',profile.uid):undefined;await store.sendMessage(room,profile.uid,text||'Imagen',media);setText('');setFile(null)}catch(e){fail(e)}finally{setBusy(false)}}}><label><ImagePlus/><input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><input value={text} placeholder="Mensaje" onChange={e=>setText(e.target.value)}/><button disabled={busy}><Send/></button></form></section>}
