import {useEffect,useRef,useState} from 'react';
import {Ban,Bell,Camera,ChevronLeft,ImagePlus,Instagram,LogOut,MessageCircle,Plus,Send,ThumbsDown,ThumbsUp,Trash2,UserPlus,Users,X} from 'lucide-react';
import {ago,topics,type Group,type GroupInvite,type Message,type Post,type Profile,type Reply,type Room} from './data';
import * as store from './store';
import './social.css';

type View='feed'|'following'|'chat';
type Person={uid:string;name:string};
const avatars=['🪐','🌙','🌱','🌊','🌻','🦊','🐢','🍄'];
const friendlyError=(value:unknown)=>{const message=value instanceof Error?value.message:'';if(message.includes('auth/email-already-in-use'))return 'Ese nombre de usuario ya está registrado.';if(message.includes('auth/invalid-credential'))return 'Usuario o contraseña incorrectos.';if(message.includes('auth/operation-not-allowed'))return 'Activa el acceso con correo y contraseña en Firebase Authentication.';if(message.toLowerCase().includes('permission')||message.includes('storage/unauthorized'))return 'No tienes permiso para realizar esta acción. Actualiza la app e inténtalo de nuevo.';if(message.includes('network'))return 'No hay conexión. Inténtalo de nuevo.';return message&&message.length<150?message:'No se pudo completar. Inténtalo de nuevo.'};

function Avatar({value,size='normal',onClick}:{value:string;size?:'normal'|'large';onClick?:()=>void}){const content=value.startsWith('http')?<img className={`s-avatar ${size}`} src={value} alt="Foto de perfil"/>:<span className={`s-avatar ${size}`}>{value}</span>;return onClick?<button className="s-avatar-button" onClick={e=>{e.stopPropagation();onClick()}}>{content}</button>:content}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="s-shade"><section className="s-modal"><header><button onClick={close}><ChevronLeft/></button><b>{title}</b><button onClick={close}><X/></button></header>{children}</section></div>}

export default function SocialApp(){
 const [profile,setProfile]=useState<Profile|null>(null),[posts,setPosts]=useState<Post[]>([]),[view,setView]=useState<View>('feed'),[topic,setTopic]=useState('Todo'),[following,setFollowing]=useState<string[]>([]),[blocked,setBlocked]=useState<string[]>([]),[detail,setDetail]=useState<Post|null>(null),[compose,setCompose]=useState(false),[room,setRoom]=useState<string|null>(null),[profileUid,setProfileUid]=useState<string|null>(null),[notice,setNotice]=useState('');
 const fail=(e:unknown)=>setNotice(friendlyError(e));
 useEffect(()=>{let stop=()=>{};store.connect().then(p=>{setProfile(p);stop=store.watchPosts(setPosts,fail)}).catch(fail);return()=>stop()},[]);
 useEffect(()=>{if(!profile?.username)return;const a=store.watchFollowing(profile.uid,setFollowing,fail),b=store.watchBlocked(profile.uid,setBlocked,fail);return()=>{a();b()}},[profile?.uid,profile?.username]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(timer)},[notice]);
 if(!profile)return <main className="social"><div className="s-loading">Cargando…</div></main>;
 if(!profile.username)return <Guest profile={profile} posts={posts} done={setProfile} fail={fail} notice={notice}/>;
 const visible=posts.filter(p=>!blocked.includes(p.uid)).filter(p=>view!=='following'||p.uid===profile.uid||following.includes(p.id)).filter(p=>topic==='Todo'||p.topic===topic);
 const openChat=async(person:Person)=>{if(person.uid===profile.uid)return;if(blocked.includes(person.uid)){fail(new Error('Has bloqueado a esta persona.'));return}try{setRoom(await store.createRoom(profile,person));setDetail(null);setView('chat')}catch(e){fail(e)}};
 return <main className="social">
  <header className="s-top"><div><Avatar value={profile.avatar} onClick={()=>setProfileUid(profile.uid)}/><span><b>Hombro Enemigo</b><small>@{profile.username}</small></span></div><div className="s-top-actions"><select aria-label="Filtrar categoría" value={topic} onChange={e=>setTopic(e.target.value)}>{topics.map(t=><option key={t}>{t}</option>)}</select><button title="Cerrar sesión" aria-label="Cerrar sesión" onClick={()=>store.logout().catch(fail)}><LogOut/></button></div></header>
  {view==='chat'?<Chats profile={profile} selected={room} setSelected={setRoom} blocked={blocked} onBlock={async id=>{await store.blockUser(profile.uid,id);setRoom(null)}} fail={fail}/>:<section className="s-feed">{visible.length?visible.map(post=><PostCard key={post.id} post={post} open={()=>setDetail(post)} profile={()=>setProfileUid(post.uid)}/>):<div className="s-empty">{view==='following'?'Aquí aparecerán tus publicaciones y aquellas donde comentes.':'No hay desahogos en esta categoría.'}</div>}</section>}
  <nav className="s-nav"><button className={view==='feed'?'active':''} onClick={()=>setView('feed')}>Inicio</button><button className={view==='following'?'active':''} onClick={()=>setView('following')}>Siguiendo</button><button className={view==='chat'?'active':''} onClick={()=>setView('chat')}>Chats</button></nav>
  {view!=='chat'&&<button className="s-plus" onClick={()=>setCompose(true)}><Plus/></button>}
  {compose&&<Composer profile={profile} close={()=>setCompose(false)} done={()=>{setCompose(false);setNotice('Publicado.')}} fail={fail}/>} 
  {detail&&<PostDetail post={detail} profile={profile} blocked={blocked} close={()=>setDetail(null)} chat={openChat} showProfile={setProfileUid} block={async id=>{await store.blockUser(profile.uid,id);setDetail(null)}} fail={fail}/>} 
  {profileUid&&<ProfileView uid={profileUid} me={profile} close={()=>setProfileUid(null)} updated={p=>{setProfile(p);setProfileUid(null)}} fail={fail}/>} 
  {notice&&<div className="s-notice">{notice}</div>}
 </main>
}

function Guest({profile,posts,done,fail,notice}:{profile:Profile;posts:Post[];done:(p:Profile)=>void;fail:(e:unknown)=>void;notice:string}){const [topic,setTopic]=useState('Todo'),[auth,setAuth]=useState(false);const visible=posts.filter(p=>topic==='Todo'||p.topic===topic);const requireAccount=()=>setAuth(true);return <main className="social"><header className="s-top s-guest-top"><div><span className="s-guest-logo">♥</span><span><b>Hombro Enemigo</b><small>Explora los desahogos</small></span></div><select aria-label="Filtrar categoría" value={topic} onChange={e=>setTopic(e.target.value)}>{topics.map(t=><option key={t}>{t}</option>)}</select></header><section className="s-feed">{visible.length?visible.map(post=><PostCard key={post.id} post={post} open={requireAccount} profile={requireAccount}/>):<div className="s-empty">No hay desahogos en esta categoría.</div>}</section><nav className="s-nav"><button className="active">Inicio</button><button onClick={requireAccount}>Siguiendo</button><button onClick={requireAccount}>Chats</button></nav><button className="s-plus" onClick={requireAccount}><Plus/></button>{auth&&<div className="s-auth-overlay"><button className="s-auth-close" aria-label="Cerrar" onClick={()=>setAuth(false)}><X/></button><Auth initial={profile} done={done} fail={fail} initialMode="login"/></div>}{notice&&<div className="s-notice">{notice}</div>}</main>}

function Auth({initial,done,fail,initialMode='register'}:{initial:Profile;done:(p:Profile)=>void;fail:(e:unknown)=>void;initialMode?:'register'|'login'}){
 const [mode,setMode]=useState<'register'|'login'>(initialMode),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[avatar,setAvatar]=useState(avatars[0]),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{if(mode==='login')done(await store.loginAccount(username,password));else{const selected=file?(await store.uploadImage(file,'profiles',initial.uid)).url:avatar;done(await store.registerAccount(username,password,name,selected))}}catch(e){fail(e)}finally{setBusy(false)}};
 return <section className="s-auth"><div className="s-brand"><span>♥</span><h1>Hombro Enemigo</h1><p>Consejo y desahogo anónimo</p></div><div className="s-auth-card"><div className="s-tabs"><button className={mode==='register'?'active':''} onClick={()=>setMode('register')}>Crear cuenta</button><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Entrar</button></div><form onSubmit={submit}>{mode==='register'&&<input required minLength={2} maxLength={30} placeholder="Nombre visible" value={name} onChange={e=>setName(e.target.value)}/>}<input required minLength={3} maxLength={20} autoCapitalize="none" placeholder="Usuario" value={username} onChange={e=>setUsername(e.target.value)}/><input required minLength={6} type="password" placeholder="Contraseña" value={password} onChange={e=>setPassword(e.target.value)}/>{mode==='register'&&<><div className="s-avatars">{avatars.map(a=><button type="button" className={avatar===a&&!file?'active':''} onClick={()=>{setAvatar(a);setFile(null)}} key={a}>{a}</button>)}</div><label className="s-file"><Camera/> {file?file.name:'Usar foto de perfil'}<input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]??null)}/></label></>}<button className="s-primary" disabled={busy}>{busy?'Espera…':mode==='register'?'Crear cuenta':'Entrar'}</button></form></div></section>
}

function PostCard({post,open,profile}:{post:Post;open:()=>void;profile:()=>void}){return <article className="s-post" onClick={open}><Avatar value={post.avatar} onClick={profile}/><div className="s-post-head"><b>@{post.name}</b><small>{ago(post.createdAt)} · {post.topic}</small></div>{post.media&&<Camera className="s-media-mark" size={18}/>}<p>{post.text}</p><footer><MessageCircle size={17}/> Abrir conversación</footer></article>}

function Composer({profile,close,done,fail}:{profile:Profile;close:()=>void;done:()=>void;fail:(e:unknown)=>void}){const [text,setText]=useState(''),[topic,setTopic]=useState(topics[1]),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false);return <Modal title="Escribir algo" close={close}><form className="s-compose" onSubmit={async e=>{e.preventDefault();setBusy(true);try{const media=file?await store.uploadImage(file,'posts',profile.uid):undefined;await store.publish({...profile,text:text.trim()||'Imagen',topic,mood:'🌤️',createdAt:Date.now(),media});done()}catch(e){fail(e)}finally{setBusy(false)}}}><select value={topic} onChange={e=>setTopic(e.target.value)}>{topics.slice(1).map(t=><option key={t}>{t}</option>)}</select><textarea autoFocus placeholder="Desahogar…" value={text} onChange={e=>setText(e.target.value)}/><label className="s-file"><ImagePlus/> {file?file.name:'Añadir imagen'}<input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><button className="s-primary" disabled={busy||(!text.trim()&&!file)}>{busy?'Publicando…':'Publicar'}</button></form></Modal>}

function PostDetail({post,profile,blocked,close,chat,showProfile,block,fail}:{post:Post;profile:Profile;blocked:string[];close:()=>void;chat:(p:Person)=>void;showProfile:(uid:string)=>void;block:(id:string)=>void;fail:(e:unknown)=>void}){
 const [replies,setReplies]=useState<Reply[]>([]),[text,setText]=useState(''),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false);
 useEffect(()=>store.watchReplies(post.id,setReplies,fail),[post.id]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!text.trim()&&!file)return;setBusy(true);try{const media=file?await store.uploadImage(file,'posts',profile.uid):undefined;await store.reply(post.id,{uid:profile.uid,name:profile.name,avatar:profile.avatar,text:text.trim()||'Imagen',createdAt:Date.now(),media});await store.followPost(profile.uid,post.id);setText('');setFile(null)}catch(e){fail(e)}finally{setBusy(false)}};
 return <Modal title="Desahogo" close={close}><section className="s-detail"><div className="s-author"><Avatar value={post.avatar} onClick={()=>showProfile(post.uid)}/><span><b>@{post.name}</b><small>{post.topic} · {ago(post.createdAt)}</small></span></div><p>{post.text}</p>{post.media&&<img className="s-detail-image" src={post.media.url} alt="Imagen del desahogo"/>}<div className="s-actions">{post.uid!==profile.uid&&<><button onClick={()=>chat(post)}><MessageCircle/> Chat privado</button><button onClick={()=>block(post.uid)}><Ban/> Bloquear</button></>}{post.uid===profile.uid&&<button className="danger" onClick={async()=>{try{await store.removePost(post.id);close()}catch(e){fail(e)}}}><Trash2/> Eliminar</button>}</div><h3>Respuestas</h3><div className="s-replies">{replies.filter(r=>!blocked.includes(r.uid)).map(reply=><ReplyRow key={reply.id} postId={post.id} reply={reply} profile={profile} chat={chat} showProfile={showProfile} block={block} fail={fail}/>) }{!replies.length&&<div className="s-empty compact">Sé la primera persona en responder.</div>}</div></section><form className="s-reply-box" onSubmit={submit}><label title="Adjuntar imagen"><ImagePlus/><input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><input maxLength={1000} value={text} placeholder={file?file.name:'Escribe una respuesta'} onChange={e=>setText(e.target.value)}/><button disabled={busy}><Send/></button></form></Modal>
}

function ReplyRow({postId,reply,profile,chat,showProfile,block,fail}:{postId:string;reply:Reply;profile:Profile;chat:(p:Person)=>void;showProfile:(uid:string)=>void;block:(id:string)=>void;fail:(e:unknown)=>void}){
 const [votes,setVotes]=useState<Record<string,number>>({});useEffect(()=>store.watchVotes(postId,reply.id,setVotes,fail),[postId,reply.id]);const mine=votes[profile.uid]??0,likes=Object.values(votes).filter(v=>v===1).length,dislikes=Object.values(votes).filter(v=>v===-1).length;const vote=(value:-1|1)=>store.voteReply(postId,reply.id,profile.uid,mine===value?0:value).catch(fail);
 return <article className="s-reply"><Avatar value={reply.avatar} onClick={()=>showProfile(reply.uid)}/><div><header><b>@{reply.name}</b><small>{ago(reply.createdAt)}</small></header><p>{reply.text}</p>{reply.media&&<img src={reply.media.url} alt="Imagen de la respuesta"/>}<footer><button className={mine===1?'active':''} onClick={()=>vote(1)}><ThumbsUp/> {likes}</button><button className={mine===-1?'active dislike':''} onClick={()=>vote(-1)}><ThumbsDown/> {dislikes}</button>{reply.uid!==profile.uid&&<><button onClick={()=>chat(reply)}><MessageCircle/> Chat</button><button onClick={()=>block(reply.uid)}><Ban/></button></>}</footer></div></article>
}

function ProfileView({uid,me,close,updated,fail}:{uid:string;me:Profile;close:()=>void;updated:(p:Profile)=>void;fail:(e:unknown)=>void}){
 const own=uid===me.uid,[person,setPerson]=useState<Profile|null>(own?me:null),[name,setName]=useState(own?me.name:''),[bio,setBio]=useState(own?me.bio??'':''),[instagram,setInstagram]=useState(own?me.instagram??'':''),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[deleting,setDeleting]=useState(false),[password,setPassword]=useState('');
 useEffect(()=>{if(own){setPerson(me);return}store.getProfile(uid).then(setPerson).catch(fail)},[uid,own]);
 if(!person)return <Modal title="Perfil" close={close}><div className="s-loading">Cargando perfil…</div></Modal>;
 if(!own)return <Modal title="Perfil" close={close}><section className="s-profile-public"><Avatar value={person.avatar} size="large"/><h2>{person.name}</h2><b>@{person.username}</b>{person.bio?<p>{person.bio}</p>:<p className="muted">Sin biografía.</p>}{person.instagram&&<a href={`https://instagram.com/${person.instagram.replace(/^@/,'')}`} target="_blank" rel="noreferrer"><Instagram/> @{person.instagram.replace(/^@/,'')}</a>}<div className="s-user-copy"><small>Usuario para invitar a grupos</small><strong>@{person.username}</strong></div></section></Modal>;
 const saveProfile=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{const avatar=file?(await store.uploadImage(file,'profiles',me.uid)).url:me.avatar;const next={...me,name:name.trim(),avatar,bio:bio.trim().slice(0,100),instagram:instagram.trim().replace(/^@/,'').slice(0,30)};await store.upsertProfile(next);updated(next)}catch(e){fail(e)}finally{setBusy(false)}};
 return <Modal title="Mi perfil" close={close}><form className="s-profile-form" onSubmit={saveProfile}><div className="s-profile-photo"><Avatar value={file?URL.createObjectURL(file):me.avatar} size="large"/><label><Camera/> Cambiar foto<input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]??null)}/></label></div><label>Nombre visible<input required minLength={2} maxLength={30} value={name} onChange={e=>setName(e.target.value)}/></label><label>Usuario<input disabled value={`@${me.username}`}/></label><label>Biografía <small>{bio.length}/100</small><textarea maxLength={100} value={bio} onChange={e=>setBio(e.target.value)} placeholder="Cuéntanos algo sobre ti"/></label><label><span className="s-instagram-label"><Instagram/> Instagram</span><input maxLength={30} value={instagram} onChange={e=>setInstagram(e.target.value)} placeholder="usuario"/></label><button className="s-primary" disabled={busy}>{busy?'Guardando…':'Guardar cambios'}</button><div className="s-delete-account">{!deleting?<button type="button" onClick={()=>setDeleting(true)}><Trash2/> Eliminar cuenta</button>:<><p>Escribe tu contraseña para eliminar la cuenta definitivamente.</p><input type="password" minLength={6} placeholder="Contraseña" value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" disabled={password.length<6||busy} onClick={async()=>{if(!confirm('¿Eliminar tu cuenta definitivamente?'))return;setBusy(true);try{await store.deleteAccount(me,password)}catch(e){fail(e);setBusy(false)}}}>Confirmar eliminación</button></>}</div></form></Modal>
}

function Chats(props:{profile:Profile;selected:string|null;setSelected:(id:string|null)=>void;blocked:string[];onBlock:(id:string)=>void;fail:(e:unknown)=>void}){
 const {profile,fail}=props,[tab,setTab]=useState<'private'|'groups'|'invites'>('private'),[groups,setGroups]=useState<Group[]>([]),[invites,setInvites]=useState<GroupInvite[]>([]),[groupId,setGroupId]=useState<string|null>(null),[creating,setCreating]=useState(false);
 useEffect(()=>{const a=store.watchGroups(profile.uid,setGroups,fail),b=store.watchGroupInvites(profile.uid,setInvites,fail);return()=>{a();b()}},[profile.uid]);
 const currentGroup=groups.find(g=>g.id===groupId);
 if(currentGroup)return <GroupChat group={currentGroup} profile={profile} close={()=>setGroupId(null)} fail={fail}/>;
 return <><div className="s-chat-tabs"><button className={tab==='private'?'active':''} onClick={()=>setTab('private')}><MessageCircle/>Privados</button><button className={tab==='groups'?'active':''} onClick={()=>setTab('groups')}><Users/>Grupos</button><button className={tab==='invites'?'active':''} onClick={()=>setTab('invites')}><Bell/>Avisos {invites.length>0&&<i>{invites.length}</i>}</button></div>
  {tab==='private'?<PrivateChats {...props}/>:tab==='groups'?<section className="s-rooms s-tab-content"><button className="s-create-group" onClick={()=>setCreating(true)}><UserPlus/> Crear grupo</button>{groups.map(g=><article key={g.id}><button className="s-room-open" onClick={()=>setGroupId(g.id)}><b>{g.name}</b><small>{g.members.length} integrantes</small></button></article>)}{!groups.length&&<div className="s-empty">Todavía no perteneces a ningún grupo.</div>}</section>:<section className="s-invites s-tab-content">{invites.map(invite=><article key={invite.id}><div><b>{invite.groupName}</b><small>@{invite.fromName} te invitó</small></div><span><button className="accept" onClick={()=>store.answerGroupInvite(invite,profile,true).catch(fail)}>Aceptar</button><button onClick={()=>store.answerGroupInvite(invite,profile,false).catch(fail)}>Rechazar</button></span></article>)}{!invites.length&&<div className="s-empty">No tienes invitaciones pendientes.</div>}</section>}
  {creating&&<CreateGroup profile={profile} close={()=>setCreating(false)} done={()=>{setCreating(false);setTab('groups')}} fail={fail}/>}</>;
}

function PrivateChats({profile,selected,setSelected,blocked,onBlock,fail}:{profile:Profile;selected:string|null;setSelected:(id:string|null)=>void;blocked:string[];onBlock:(id:string)=>void;fail:(e:unknown)=>void}){
 const [rooms,setRooms]=useState<Room[]>([]),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(''),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false);const end=useRef<HTMLDivElement>(null);
 useEffect(()=>store.watchRooms(profile.uid,setRooms,fail),[profile.uid]);useEffect(()=>{if(!selected){setMessages([]);return}return store.watchMessages(selected,setMessages,fail)},[selected]);useEffect(()=>{end.current?.scrollIntoView()},[messages]);
 const allowed=rooms.filter(r=>!r.members.some(id=>id!==profile.uid&&blocked.includes(id))),current=allowed.find(r=>r.id===selected),other=(r:Room)=>r.members.find(id=>id!==profile.uid)??'',name=(r:Room)=>r.names[other(r)]??'Chat';
 if(!current)return <section className="s-rooms">{allowed.map(r=><article key={r.id}><button className="s-room-open" onClick={()=>setSelected(r.id)}><b>{name(r)}</b><small>Conversación privada</small></button><button className="s-room-delete" title="Eliminar chat" onClick={async()=>{try{await store.deleteRoom(r.id);if(selected===r.id)setSelected(null)}catch(e){fail(e)}}}><Trash2/></button></article>)}{!allowed.length&&<div className="s-empty">Abre un desahogo o una respuesta para iniciar un chat.</div>}</section>;
 const send=async(e:React.FormEvent)=>{e.preventDefault();if(!text.trim()&&!file)return;setBusy(true);try{const media=file?await store.uploadImage(file,'chats',profile.uid):undefined;await store.sendMessage(selected,profile.uid,text.trim()||'Imagen',media);setText('');setFile(null)}catch(e){fail(e)}finally{setBusy(false)}};
 return <section className="s-chat"><header><button onClick={()=>setSelected(null)}><ChevronLeft/></button><b>{name(current)}</b><span><button title="Bloquear" onClick={()=>onBlock(other(current))}><Ban/></button><button title="Eliminar chat" onClick={async()=>{try{await store.deleteRoom(current.id);setSelected(null)}catch(e){fail(e)}}}><Trash2/></button></span></header><div className="s-messages">{messages.map(m=><article className={m.uid===profile.uid?'mine':''} key={m.id}>{m.text&&<p>{m.text}</p>}{m.media&&<img src={m.media.url} alt="Imagen del chat"/>}</article>)}<div ref={end}/></div><form onSubmit={send}><label className={file?'selected':''}><ImagePlus/><input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><input value={text} placeholder={file?file.name:'Mensaje'} onChange={e=>setText(e.target.value)}/><button disabled={busy}><Send/></button></form></section>
}

function CreateGroup({profile,close,done,fail}:{profile:Profile;close:()=>void;done:()=>void;fail:(e:unknown)=>void}){const [name,setName]=useState(''),[users,setUsers]=useState(''),[busy,setBusy]=useState(false);return <Modal title="Crear grupo" close={close}><form className="s-group-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await store.createGroup(profile,name,users.split(/[ ,;\n]+/));done()}catch(e){fail(e)}finally{setBusy(false)}}}><input required maxLength={40} placeholder="Nombre del grupo" value={name} onChange={e=>setName(e.target.value)}/><textarea required placeholder="Usuarios a invitar: angel, maria, pedro" value={users} onChange={e=>setUsers(e.target.value)}/><small>Separa los usuarios con espacios o comas.</small><button className="s-primary" disabled={busy}>{busy?'Creando…':'Crear y enviar invitaciones'}</button></form></Modal>}

function GroupChat({group,profile,close,fail}:{group:Group;profile:Profile;close:()=>void;fail:(e:unknown)=>void}){const [messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(''),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false);const end=useRef<HTMLDivElement>(null);useEffect(()=>store.watchGroupMessages(group.id,setMessages,fail),[group.id]);useEffect(()=>{end.current?.scrollIntoView()},[messages]);const send=async(e:React.FormEvent)=>{e.preventDefault();if(!text.trim()&&!file)return;setBusy(true);try{const media=file?await store.uploadImage(file,'chats',profile.uid):undefined;await store.sendGroupMessage(group.id,profile.uid,text.trim()||'Imagen',media);setText('');setFile(null)}catch(e){fail(e)}finally{setBusy(false)}};return <section className="s-chat"><header><button onClick={close}><ChevronLeft/></button><b>{group.name}</b><small>{group.members.length} integrantes</small></header><div className="s-messages">{messages.map(m=><article className={m.uid===profile.uid?'mine':''} key={m.id}><small>{m.uid===profile.uid?'Tú':group.names[m.uid]??'Integrante'}</small>{m.text&&<p>{m.text}</p>}{m.media&&<img src={m.media.url} alt="Imagen del grupo"/>}</article>)}<div ref={end}/></div><form onSubmit={send}><label className={file?'selected':''}><ImagePlus/><input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><input value={text} placeholder={file?file.name:'Mensaje al grupo'} onChange={e=>setText(e.target.value)}/><button disabled={busy}><Send/></button></form></section>}
