import { initializeApp } from 'firebase/app';
import { EmailAuthProvider, browserLocalPersistence, createUserWithEmailAndPassword, getAuth, linkWithCredential, setPersistence, signInAnonymously, signInWithEmailAndPassword, signOut } from 'firebase/auth';
import { getFirestore, collection, doc, getDoc, setDoc, addDoc, deleteDoc, onSnapshot, query, orderBy, limit, where, runTransaction, updateDoc, arrayUnion } from 'firebase/firestore';
import { getStorage, ref as storageRef, uploadBytes, getDownloadURL } from 'firebase/storage';
import type { Profile, Post, Reply, Room, Message, Group, GroupInvite } from './data';
import { examples, exampleReplies } from './data';
const env=import.meta.env;
export const cloud=Boolean(env.VITE_FIREBASE_API_KEY && env.VITE_FIREBASE_PROJECT_ID && env.VITE_FIREBASE_APP_ID);
const app=cloud?initializeApp({apiKey:env.VITE_FIREBASE_API_KEY,authDomain:env.VITE_FIREBASE_AUTH_DOMAIN,projectId:env.VITE_FIREBASE_PROJECT_ID,storageBucket:env.VITE_FIREBASE_STORAGE_BUCKET,messagingSenderId:env.VITE_FIREBASE_MESSAGING_SENDER_ID,appId:env.VITE_FIREBASE_APP_ID}):null;
const db=app?getFirestore(app):null;
const storage=app?getStorage(app):null;
export function read<T>(key:string,fallback:T):T {try {const v=localStorage.getItem('he:'+key);return v?JSON.parse(v):fallback;}catch{return fallback;}}
export function save(key:string,value:unknown){localStorage.setItem('he:'+key,JSON.stringify(value));window.dispatchEvent(new Event('he-change'));}
function localWatch<T>(key:string,fallback:T,cb:(v:T)=>void){const run=()=>cb(read(key,fallback));run();window.addEventListener('he-change',run);window.addEventListener('storage',run);return()=>{window.removeEventListener('he-change',run);window.removeEventListener('storage',run);};}
function defined<T extends Record<string,unknown>>(value:T){return Object.fromEntries(Object.entries(value).filter(([,v])=>v!==undefined)) as T;}
async function persistentAuth(){if(!app)throw new Error('Firebase no está conectado.');const auth=getAuth(app);await setPersistence(auth,browserLocalPersistence);return auth;}
export async function connect():Promise<Profile>{let profile=read<Profile>('profile',{uid:crypto.randomUUID(),name:'',avatar:'🪐'});if(app&&db){const auth=await persistentAuth();await auth.authStateReady();const user=auth.currentUser??(await signInAnonymously(auth)).user;if(!user.isAnonymous){const snap=await getDoc(doc(db,'users',user.uid));profile=snap.exists()?({uid:user.uid,...snap.data()} as Profile):{uid:user.uid,name:'',avatar:'🪐'};}else profile={...profile,uid:user.uid,username:undefined};}save('profile',profile);return profile;}
export async function upsertProfile(profile:Profile){save('profile',profile);if(db)await setDoc(doc(db,'users',profile.uid),{name:profile.name,avatar:profile.avatar,username:profile.username??'',updatedAt:Date.now()},{merge:true});}
const accountEmail=(username:string)=>`${username.trim().toLowerCase().replace(/[^a-z0-9._-]/g,'')}@hombro-enemigo.invalid`;
export async function registerAccount(username:string,password:string,name:string,avatar:string):Promise<Profile>{if(!app||!db)throw new Error('Firebase no está conectado.');const clean=username.trim().toLowerCase();if(!/^[a-z0-9._-]{3,20}$/.test(clean))throw new Error('El usuario debe tener 3 a 20 letras, números, punto, guion o guion bajo.');if(password.length<6)throw new Error('La contraseña debe tener al menos 6 caracteres.');const auth=await persistentAuth(),anonymous=auth.currentUser;if(!anonymous)throw new Error('No se pudo iniciar el registro. Recarga la página.');await runTransaction(db,async tx=>{const ref=doc(db,'usernames',clean),snap=await tx.get(ref);if(snap.exists())throw new Error('Ese usuario ya existe.');tx.set(ref,{uid:anonymous.uid,createdAt:Date.now()});});let user;try{user=anonymous.isAnonymous?(await linkWithCredential(anonymous,EmailAuthProvider.credential(accountEmail(clean),password))).user:(await createUserWithEmailAndPassword(auth,accountEmail(clean),password)).user;}catch(error){await deleteDoc(doc(db,'usernames',clean));throw error;}const profile={uid:user.uid,name:name.trim()||clean,avatar,username:clean};await upsertProfile(profile);return profile;}
export async function loginAccount(username:string,password:string):Promise<Profile>{if(!app||!db)throw new Error('Firebase no está conectado.');const auth=await persistentAuth(),user=(await signInWithEmailAndPassword(auth,accountEmail(username),password)).user;const snap=await getDoc(doc(db,'users',user.uid));if(!snap.exists())throw new Error('No encontramos el perfil.');const profile={uid:user.uid,...snap.data()} as Profile;save('profile',profile);return profile;}
export async function logout(){if(app)await signOut(getAuth(app));localStorage.removeItem('he:profile');location.reload();}
export async function uploadImage(file:File,folder:'posts'|'chats'|'profiles',uid:string):Promise<import('./data').Media>{if(!storage)throw new Error('Firebase Storage no está configurado.');if(!file.type.startsWith('image/'))throw new Error('Selecciona un archivo de imagen.');if(file.size>15*1024*1024)throw new Error('La imagen es demasiado grande. Máximo 15 MB.');const extension=file.type.split('/')[1]?.replace('jpeg','jpg')||'jpg';const path=`${folder}/${uid}/${Date.now()}-${crypto.randomUUID()}.${extension}`;const target=storageRef(storage,path);await uploadBytes(target,file,{contentType:file.type,customMetadata:{expiresAt:String(Date.now()+7*24*60*60*1000)}});return{path,url:await getDownloadURL(target)};}
export function watchPosts(cb:(v:Post[])=>void,fail:(e:Error)=>void){return db?onSnapshot(query(collection(db,'posts'),orderBy('createdAt','desc'),limit(100)),s=>cb(s.docs.map(d=>({...d.data(),id:d.id}) as Post)),fail):localWatch<Post[]>('posts',examples,cb);}
export async function publish(p:Omit<Post,'id'>){const payload=defined({uid:p.uid,name:p.name,avatar:p.avatar,text:p.text,topic:p.topic,mood:p.mood,createdAt:p.createdAt,media:p.media});if(db){await addDoc(collection(db,'posts'),payload);}else{save('posts',[{...p,id:crypto.randomUUID()},...read('posts',examples)]);}}
export async function removePost(id:string){if(db)await deleteDoc(doc(db,'posts',id));else save('posts',read<Post[]>('posts',examples).filter(p=>p.id!==id));}
export function watchReplies(id:string,cb:(v:Reply[])=>void,fail:(e:Error)=>void){return db?onSnapshot(query(collection(db,'posts',id,'replies'),orderBy('createdAt'),limit(200)),s=>cb(s.docs.map(d=>({...d.data(),id:d.id}) as Reply)),fail):localWatch<Reply[]>('replies:'+id,exampleReplies[id]??[],cb);}
export async function reply(id:string,p:Omit<Reply,'id'>){if(db)await addDoc(collection(db,'posts',id,'replies'),defined(p));else save('replies:'+id,[...read<Reply[]>('replies:'+id,exampleReplies[id]??[]),{...p,id:crypto.randomUUID()}]);}
export async function followPost(uid:string,postId:string){if(db)await setDoc(doc(db,'users',uid,'following',postId),{postId,createdAt:Date.now()});else save('following:'+uid,[...new Set([...read<string[]>('following:'+uid,[]),postId])]);}
export function watchFollowing(uid:string,cb:(ids:string[])=>void,fail:(e:Error)=>void){return db?onSnapshot(collection(db,'users',uid,'following'),s=>cb(s.docs.map(d=>d.id)),fail):localWatch<string[]>('following:'+uid,[],cb);}
export function watchVotes(postId:string,replyId:string,cb:(votes:Record<string,number>)=>void,fail:(e:Error)=>void){return db?onSnapshot(collection(db,'posts',postId,'replies',replyId,'votes'),s=>cb(Object.fromEntries(s.docs.map(d=>[d.id,Number(d.data().value)]))),fail):localWatch<Record<string,number>>(`votes:${postId}:${replyId}`,{},cb);}
export async function voteReply(postId:string,replyId:string,uid:string,value:-1|1|0){if(db){const ref=doc(db,'posts',postId,'replies',replyId,'votes',uid);if(value===0)await deleteDoc(ref);else await setDoc(ref,{uid,value});}else{const votes=read<Record<string,number>>(`votes:${postId}:${replyId}`,{});if(value===0)delete votes[uid];else votes[uid]=value;save(`votes:${postId}:${replyId}`,votes);}}
export async function blockUser(uid:string,otherUid:string){if(db)await setDoc(doc(db,'users',uid,'blocked',otherUid),{uid:otherUid,createdAt:Date.now()});else save('blocked:'+uid,[...new Set([...read<string[]>('blocked:'+uid,[]),otherUid])]);}
export function watchBlocked(uid:string,cb:(ids:string[])=>void,fail:(e:Error)=>void){return db?onSnapshot(collection(db,'users',uid,'blocked'),s=>cb(s.docs.map(d=>d.id)),fail):localWatch<string[]>('blocked:'+uid,[],cb);}
export function watchHearts(id:string,cb:(v:string[])=>void,fail:(e:Error)=>void){return db?onSnapshot(collection(db,'posts',id,'hearts'),s=>cb(s.docs.map(d=>d.id)),fail):localWatch<string[]>('hearts:'+id,[],cb);}
export async function heart(id:string,uid:string,on:boolean){if(db){if(on)await setDoc(doc(db,'posts',id,'hearts',uid),{uid});else await deleteDoc(doc(db,'posts',id,'hearts',uid));}else{const list=read<string[]>('hearts:'+id,[]);save('hearts:'+id,on?[...new Set([...list,uid])]:list.filter(x=>x!==uid));}}
export async function report(postId:string,uid:string,reason:string){const value={postId,uid,reason,createdAt:Date.now()};if(db)await addDoc(collection(db,'reports'),value);else save('reports',[...read<unknown[]>('reports',[]),value]);}
export function watchRooms(uid:string,cb:(v:Room[])=>void,fail:(e:Error)=>void){return db?onSnapshot(query(collection(db,'rooms'),where('members','array-contains',uid)),s=>cb(s.docs.map(d=>({...d.data(),id:d.id}) as Room)),fail):localWatch<Room[]>('rooms',[],cb);}
export async function createRoom(me:Profile,other:{uid:string;name:string}){const id=[me.uid,other.uid].sort().join('_');const room:Room={id,members:[me.uid,other.uid],names:{[me.uid]:me.name,[other.uid]:other.name},createdAt:Date.now()};if(db){const existing=await getDoc(doc(db,'rooms',id));if(!existing.exists())await setDoc(doc(db,'rooms',id),room);}else{const all=read<Room[]>('rooms',[]);if(!all.some(r=>r.id===id))save('rooms',[room,...all]);}return id;}
export function watchMessages(id:string,cb:(v:Message[])=>void,fail:(e:Error)=>void){return db?onSnapshot(query(collection(db,'rooms',id,'messages'),orderBy('createdAt','desc'),limit(200)),s=>cb(s.docs.map(d=>({...d.data(),id:d.id}) as Message).reverse()),fail):localWatch<Message[]>('messages:'+id,[],cb);}
export async function sendMessage(id:string|null,uid:string,text:string,media?:import('./data').Media):Promise<Message>{if(!id)throw new Error('Selecciona una conversación.');const msg=defined({uid,text,createdAt:Date.now(),media}) as Omit<Message,'id'>;if(db){const saved=await addDoc(collection(db,'rooms',id,'messages'),msg);return {...msg,id:saved.id};}const local={...msg,id:crypto.randomUUID()};save('messages:'+id,[...read<Message[]>('messages:'+id,[]),local]);return local;}
export async function deleteRoom(id:string){if(db)await deleteDoc(doc(db,'rooms',id));else save('rooms',read<Room[]>('rooms',[]).filter(r=>r.id!==id));}
export function watchGroups(uid:string,cb:(v:Group[])=>void,fail:(e:Error)=>void){return db?onSnapshot(query(collection(db,'groups'),where('members','array-contains',uid)),s=>cb(s.docs.map(d=>({...d.data(),id:d.id}) as Group)),fail):localWatch<Group[]>('groups',[],cb);}
export function watchGroupInvites(uid:string,cb:(v:GroupInvite[])=>void,fail:(e:Error)=>void){return db?onSnapshot(collection(db,'users',uid,'groupInvites'),s=>cb(s.docs.map(d=>({...d.data(),id:d.id}) as GroupInvite).filter(i=>i.status==='pending')),fail):localWatch<GroupInvite[]>('groupInvites:'+uid,[],cb);}
export async function createGroup(me:Profile,name:string,usernames:string[]){if(!db)throw new Error('Firebase no está conectado.');const clean=[...new Set(usernames.map(v=>v.trim().toLowerCase().replace(/^@/, '')).filter(Boolean))].filter(v=>v!==me.username);if(!name.trim())throw new Error('Escribe un nombre para el grupo.');if(!clean.length)throw new Error('Agrega al menos un usuario.');const people:Profile[]=[];for(const username of clean){const usernameSnap=await getDoc(doc(db,'usernames',username));if(!usernameSnap.exists())throw new Error(`No existe @${username}.`);const uid=String(usernameSnap.data().uid),userSnap=await getDoc(doc(db,'users',uid));if(!userSnap.exists())throw new Error(`No encontramos el perfil @${username}.`);people.push({uid,...userSnap.data()} as Profile);}const groupRef=await addDoc(collection(db,'groups'),{name:name.trim().slice(0,40),ownerId:me.uid,members:[me.uid],names:{[me.uid]:me.name},createdAt:Date.now()});for(const person of people){await setDoc(doc(db,'users',person.uid,'groupInvites',groupRef.id),{groupId:groupRef.id,groupName:name.trim().slice(0,40),fromUid:me.uid,fromName:me.name,toUid:person.uid,toUsername:person.username??'',status:'pending',createdAt:Date.now()});}return groupRef.id;}
export async function answerGroupInvite(invite:GroupInvite,me:Profile,accept:boolean){if(!db)throw new Error('Firebase no está conectado.');if(accept)await updateDoc(doc(db,'groups',invite.groupId),{members:arrayUnion(me.uid),[`names.${me.uid}`]:me.name});await updateDoc(doc(db,'users',me.uid,'groupInvites',invite.id),{status:accept?'accepted':'declined'});}
export function watchGroupMessages(id:string,cb:(v:Message[])=>void,fail:(e:Error)=>void){return db?onSnapshot(query(collection(db,'groups',id,'messages'),orderBy('createdAt','desc'),limit(200)),s=>cb(s.docs.map(d=>({...d.data(),id:d.id}) as Message).reverse()),fail):localWatch<Message[]>('groupMessages:'+id,[],cb);}
export async function sendGroupMessage(id:string,uid:string,text:string,media?:import('./data').Media){if(!db)throw new Error('Firebase no está conectado.');return addDoc(collection(db,'groups',id,'messages'),defined({uid,text,createdAt:Date.now(),media}));}
